liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.root_dir%/../public"
                cache_prefix: "imagine/cache"

    loaders:
        defaults:
            filesystem:
                data_root: "%kernel.root_dir%/../public"


    driver:               gd
    cache:                default
    data_loader:          default
    default_image:        null
    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeAction


    filter_sets:


        # an example thumbnail transformation definition
        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
        squared_thumbnail:

            # set your image quality defaults
            jpeg_quality:          85
            png_compression_level: 8

            # setup the filter steps to apply for this transformation
            filters:

                # auto rotate the image using EXIF metadata
                auto_rotate: ~

                # strip the image of all metadata
                strip: ~

                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [253, 253]
                    mode:          outbound
                    allow_upscale: true

                # create border by placing image on larger black background
                background:
                    size:     [256, 256]
                    position: center
                    color:    '#fff'

        homeList:

            quality: 85

            filters:

                thumbnail:
                    size: [286, 100]


        avatar:
            quality: 85

            filters:

                thumbnail:
                    size: [44,44]


        show:
            filters:

                thumbnail:

                    size: [ 1200,600 ]

                    allow_upscale: true

